// src/lib/pdf-generator.ts

import { jsPDF } from "jspdf";
import { toast } from "sonner";

export interface NoteSection {
  timestamp: string;
  section_title: string;
  content: string;
}

export interface NotesData {
  video_title: string;
  notes: NoteSection[];
}

/**
 * Generate and download a PDF from the current study notes.
 */
export function downloadNotesAsPDF(notesData: NotesData | null) {
  if (!notesData || !notesData.notes || notesData.notes.length === 0) {
    toast.error('No notes available to download');
    return;
  }

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper: add a new page if needed
  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
      return true;
    }
    return false;
  }

  // Header - Purple header bar
  doc.setFillColor(79, 70, 229);  // brand-600
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('EduTube AI — Study Notes', margin, 16);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(200, 200, 255);
  doc.text('AI-generated from YouTube video transcript', margin, 24);

  // Date
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });
  doc.setFontSize(9);
  doc.text(dateStr, pageWidth - margin, 24, { align: 'right' });

  y = 45;

  // Video Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 50);
  const titleLines = doc.splitTextToSize(notesData.video_title, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 4;

  // Divider line
  doc.setDrawColor(220, 220, 230);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Notes Sections
  notesData.notes.forEach((note, idx) => {
    checkPageBreak(30);

    // Timestamp badge
    doc.setFillColor(238, 242, 255);  // brand-50
    doc.roundedRect(margin, y - 4, 22, 7, 1, 1, 'F');
    doc.setFont('courier', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(79, 70, 229);
    doc.text(note.timestamp, margin + 2, y + 1);

    // Section title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 50);
    doc.text(note.section_title, margin + 26, y + 1);
    y += 9;

    // Content — bullet points
    const lines = note.content.split('\n');
    lines.forEach(line => {
      const trimmed = line.trim();
      if (!trimmed) return;

      checkPageBreak(7);

      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');
      const text = isBullet ? trimmed.replace(/^[•\-\*]\s*/, '') : trimmed;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 70);

      const wrapped = doc.splitTextToSize(text, contentWidth - 10);

      if (isBullet) {
        // Draw bullet dot
        doc.setFillColor(99, 102, 241);
        doc.circle(margin + 3, y - 0.5, 1, 'F');
        doc.text(wrapped, margin + 8, y);
      } else {
        doc.text(wrapped, margin + 4, y);
      }

      y += wrapped.length * 5 + 2;
    });

    y += 5;

    // Section divider (except last)
    if (idx < notesData.notes.length - 1) {
      checkPageBreak(5);
      doc.setDrawColor(230, 230, 240);
      doc.setLineWidth(0.3);
      doc.line(margin + 4, y, pageWidth - margin - 4, y);
      y += 6;
    }
  });

  // Footer on last page
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 170);
  doc.text('Generated by EduTube AI — Powered by YouTube Data API + Grok AI', margin, pageHeight - 10);

  // Save
  const safeTitle = notesData.video_title
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 50);
  doc.save(`EduTube_Notes_${safeTitle}.pdf`);

  toast.success('📄 PDF downloaded successfully!');
}
